name: Build and Package Coffee Break

on:
    push:
        branches:
            - master
        tags:
            - 'v*.*.*'


jobs:
    build:
        runs-on: windows-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                    dotnet-version: '6.0.x'
        
            - name: Restore
              run: dotnet restore

            - name: Build and publish app
              run: dotnet publish CoffeeBreak.csproj -c Release -r win-x64 --self-contained false

            - name: Install Inno Setup
              run: |
                  Invoke-WebRequest https://jrsoftware.org/download.php/is.exe -OutFile is.exe
                  Start-Process -FilePath .\is.exe -ArgumentList \"/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /DIR=innosetup\" -Wait

            - name: Compile Inno Setup Script
              run: |
                  .\innosetup\ISCC.exe installer\coffee_break.iss

            - name: Upload installer artifact
              uses: actions/upload-artifact@v3
              with:
                name: CoffeeBreakInstaller
                path: output/CoffeeBreakInstaller.exe
